version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
        SONAR_TOKEN: "525eb1be32f4451c3bc04ef9a0c0f27610f48c79"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - npm install -g sonarqube-scanner
        - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.organization=alainhenryt -Dsonar.projectKey=weblab-cicd-angulartestapp
  build:
    commands:
        - echo Build started 
        - echo "$(/codebuild/*)"
        - ng build --prod
        - echo "$(dist/)"
artifacts:
    files:
        - '**/*'
    type: zip
    base-directory: '.dist/'
    discard-paths: yes